### ISSUE TITLE
forEachConfiguredDevice Error

### ISSUE THREAD

**Issue by BeerMacht** [soef/ioBroker.tr-064#13]
FRITZ!Box Fon WLAN 7360 (EWE Edition)
FRITZ!OS 06.30

This error occurs after I added the box by using the plus button:

> 

host.xxxx	2017-01-13 08:36:47.019	info	Restart adapter system.adapter.tr-064.0 because enabled
host.xxxx	2017-01-13 08:36:47.018	error	instance system.adapter.tr-064.0 terminated with code 0 (OK)
tr-064.0	2017-01-13 08:36:47.002	info	terminating
tr-064.0	2017-01-13 08:36:46.993	error	at Timer.listOnTimeout (timers.js:92:15)
tr-064.0	2017-01-13 08:36:46.993	error	at doIt [as _onTimeout] (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:496:32)
tr-064.0	2017-01-13 08:36:46.993	error	at TR064.getWLANGuest (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:364:76)
tr-064.0	2017-01-13 08:36:46.993	error	TypeError: Cannot read property 'actions' of undefined
tr-064.0	2017-01-13 08:36:46.987	error	uncaught exception: Cannot read property 'actions' of undefined
tr-064.0	2017-01-13 08:36:46.099	debug	forEachConfiguredDevice: null
tr-064.0	2017-01-13 08:36:46.097	error	forEachConfiguredDevice: in GetSpecificHostEntryExt 0(AVM/xx-xx-xx-xx-xx-xx):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {'code':500}
tr-064.0	2017-01-13 08:36:46.082	debug	forEachConfiguredDevice
tr-064.0	2017-01-13 08:36:46.081	debug	updateDevices
tr-064.0	2017-01-13 08:36:46.080	debug	in updateAll
tr-064.0	2017-01-13 08:36:44.136	debug	callmonitor connected
tr-064.0	2017-01-13 08:36:44.079	debug	starting callmonitor
tr-064.0	2017-01-13 08:36:43.921	debug	Phoebook.read: NewPhonebookList=0
tr-064.0	2017-01-13 08:36:43.889	debug	Phoebook.read
tr-064.0	2017-01-13 08:36:43.887	debug	getVoIPCommonAreaCode:
tr-064.0	2017-01-13 08:36:43.860	debug	getVoIPCommonCountryCode: 0049
tr-064.0	2017-01-13 08:36:43.627	error	forEachConfiguredDevice: in GetSpecificHostEntryExt 0(AVM/xx-xx-xx-xx-xx-xx):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {'code':500}
tr-064.0	2017-01-13 08:36:43.572	debug	forEachConfiguredDevice
tr-064.0	2017-01-13 08:36:43.569	debug	createConfiguredDevices
tr-064.0	2017-01-13 08:36:41.940	info	starting. Version 0.1.19 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.7.2
tr-064.0	2017-01-13 08:36:41.856	debug	statesDB connected
tr-064.0	2017-01-13 08:36:41.830	debug	objectDB connected
host.xxxx	2017-01-13 08:36:39.541	info	instance system.adapter.tr-064.0 started with pid 1504
host.xxxx	2017-01-13 08:36:31.810	info	Restart adapter system.adapter.tr-064.0 because enabled

>

**Comment by soef** [comment]
Hello, this problem ist fixed in version 0.1.20
