### ISSUE TITLE
Fehlermeldungen im iobroker log

### ISSUE THREAD

**Issue by looxer01** [soef/ioBroker.tr-064#14]
Hi,
Ich habe eine Fritzbox 7490 mit softwaresatnd 06.60

nach update auf 0.1.19 bekomme ich folgende Fehlermeldungen im Log:
tr-064.0	2017-01-13 15:30:39.014	error	code=unknown error code Device responded with fault Error: Credentials incorrect
tr-064.0	2017-01-13 14:30:44.518	error	code=500 sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500
tr-064.0	2017-01-13 14:30:33.808	error	code=unknown error code Device responded with fault Error: Credentials incorrect
tr-064.0	2017-01-13 14:17:16.502	error	forEachConfiguredDevice: in GetSpecificHostEntryExt 10(Teresas-iPhone/8C:8E:F2:CB:6F:0D):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1:
tr-064.0	2017-01-13 14:05:24.386	info	starting. Version 0.1.19 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.6.0
tr-064.0	2017-01-13 14:05:21.243	info	terminating

vG Looxer

**Comment by soef** [comment]
Hello,

are you sure that this error does not occur in the previous version of iobroker.tr-064? It occurs when getting Information from the device "Teresas-iPhone".

**Comment by looxer01** [comment]
Hi,
I am pretty sure as it never came up before I updated.
Before I had version 0.1.12 installed. 
it also occurs for other devises:
tr-064.0	2017-01-13 18:29:37.110	error	forEachConfiguredDevice: in GetSpecificHostEntryExt 1(Oekofen/00:60:B5:33:46:23):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: - {"code

vG Looxer

**Comment by soef** [comment]
Hi, can u check if the used username and assword in the iobroker.tr-64 configuration is correct?

**Comment by looxer01** [comment]
Hi,
I am sure that it is correct. I am using it for my presence control. And it actually works which would not be the case otherwise. 

I just restarted my box. Perhaps it will fix it. In only restarted TR-064. Sometimes it makes a difference.
I will let you know.

looxer

**Comment by looxer01** [comment]
Hi,
no, restart did not help. the first message after restart is this one:
tr-064.0	2017-01-13 19:32:25.557	error	code=unknown error code Device responded with fault Error: Credentials incorrect

Looxer

**Comment by looxer01** [comment]
![tr064](https://cloud.githubusercontent.com/assets/11609655/21941183/d8123646-d9c7-11e6-99db-b8555ebd37c8.JPG)

Hi 
my config is attached. Hope it helps

br Looxer

**Comment by looxer01** [comment]
Hi,
just upgraded to 0.1.20 upgegraded restarted the fritbox
all quite at the moment
I will close the case if nothing comes up anymore

Looxer

**Comment by wowik2018** [comment]
Hallo, ich bekomme diese Fehler. Bitte helfen Sie mir.
tr-064.0 | 2019-11-26 12:06:13.738 | error | (24618) ~
-- | -- | -- | --
tr-064.0 | 2019-11-26 12:06:13.737 | error | (24618) ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2019-11-26 12:06:13.737 | error | (24618) ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2019-11-26 12:06:13.736 | error | (24618) ~
tr-064.0 | 2019-11-26 12:06:13.735 | error | (24618) Error: getaddrinfo ENOTFOUND http http:80 - {"errno":"ENOTFOUND","code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"http","host":"http","port":80}
tr-064.0 | 2019-11-26 12:06:13.522 | info | (24618) starting. Version 0.4.14 in /home/pi/node_modules/iobroker.tr-064, node: v10.17.0
tr-064.0 | 2019-11-26 12:06:12.104 | debug | (24618) statesDB connected
tr-064.0 | 2019-11-26 12:06:12.102 | debug | (24618) States create PubSub Client
tr-064.0 | 2019-11-26 12:06:12.089 | debug | (24618) Objects connected to redis: 127.0.0.1:9001
tr-064.0 | 2019-11-26 12:06:12.084 | debug | (24618) Redis States: Use Redis connection: 127.0.0.1:9000
tr-064.0 | 2019-11-26 12:06:12.079 | debug | (24618) objectDB connected
tr-064.0 | 2019-11-26 12:06:12.046 | debug | (24618) Objects client initialize lua scripts
tr-064.0 | 2019-11-26 12:06:12.044 | debug | (24618) Objects create PubSub Client
tr-064.0 | 2019-11-26 12:06:12.034 | debug | (24618) Objects client ready ... initialize now
tr-064.0 | 2019-11-26 12:06:11.917 | debug | (24618) Redis Objects: Use Redis connection: 127.0.0.1:9001
