### ISSUE TITLE
 Cannot read property 'actions' of undefined at TR064.setWLANGuest

### ISSUE THREAD

**Issue by vore** [soef/ioBroker.tr-064#15]
Hi,
I'm having issues with the Guest wifi. I always get an error message when switching the Guest wifi.
Im using the current version 0.1.20

Log says the following:

TypeError:	2017-01-14 14:55:35.804	error	at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:1062:21)
TypeError:	2017-01-14 14:55:35.804	error	at Object.onStateChange (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:112:27)
TypeError:	2017-01-14 14:55:35.804	error	at TR064.setWLANGuest (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:283:81)
TypeError:	2017-01-14 14:55:35.804	error	Cannot read property 'actions' of undefined

**Comment by soef** [comment]
Hello, can you please update to version 0.1.26. With this version you can create a dump of the available services of your firtzbox. 

To create a dump set the state tr-064.0.states.command to dumpservices. The response will be stored in the state commandResult

**Comment by vore** [comment]
Hello, 
got the file. What should I look for?
Regards

**Comment by soef** [comment]
Can you send it to me? Or post it here=

**Comment by vore** [comment]
Hello!

This is what I get:

{"urn:dslforum-org:service:DeviceInfo:1":{"actions":{"GetInfo":"fn","SetProvisioningCode":"fn","GetDeviceLog":"fn","GetSecurityPort":"fn"}},"urn:dslforum-org:service:DeviceConfig:1":{"actions":{"GetPersistentData":"fn","SetPersistentData":"fn","ConfigurationStarted":"fn","ConfigurationFinished":"fn","FactoryReset":"fn","Reboot":"fn","X_GenerateUUID":"fn","X_AVM-DE_GetConfigFile":"fn","X_AVM-DE_SetConfigFile":"fn","X_AVM-DE_CreateUrlSID":"fn"}},"urn:dslforum-org:service:Layer3Forwarding:1":{"actions":{"SetDefaultConnectionService":"fn","GetDefaultConnectionService":"fn","GetForwardNumberOfEntries":"fn","AddForwardingEntry":"fn","DeleteForwardingEntry":"fn","GetSpecificForwardingEntry":"fn","GetGenericForwardingEntry":"fn","SetForwardingEntryEnable":"fn"}},"urn:dslforum-org:service:LANConfigSecurity:1":{"actions":{"GetInfo":"fn","X_AVM-DE_GetCurrentUser":"fn","X_AVM-DE_GetAnonymousLogin":"fn","SetConfigPassword":"fn"}},"urn:dslforum-org:service:ManagementServer:1":{"actions":{"GetInfo":"fn","SetManagementServerURL":"fn","SetManagementServerUsername":"fn","SetManagementServerPassword":"fn","SetPeriodicInform":"fn","SetConnectionRequestAuthentication":"fn","SetUpgradeManagement":"fn","X_SetTR069Enable":"fn","X_AVM-DE_GetTR069FirmwareDownloadEnabled":"fn","X_AVM-DE_SetTR069FirmwareDownloadEnabled":"fn"}},"urn:dslforum-org:service:Time:1":{"actions":{"GetInfo":"fn","SetNTPServers":"fn"}},"urn:dslforum-org:service:UserInterface:1":{"actions":{"GetInfo":"fn","X_AVM-DE_CheckUpdate":"fn","X_AVM-DE_DoUpdate":"fn","X_AVM-DE_DoPrepareCGI":"fn","X_AVM-DE_DoManualUpdate":"fn","X_AVM-DE_GetInternationalConfig":"fn","X_AVM-DE_SetInternationalConfig":"fn","X_AVM-DE_GetInfo":"fn","X_AVM-DE_SetConfig":"fn"}},"urn:dslforum-org:service:X_VoIP:1":{"actions":{"GetInfoEx":"fn","X_AVM-DE_AddVoIPAccount":"fn","X_AVM-DE_GetVoIPAccount":"fn","X_AVM-DE_DelVoIPAccount":"fn","GetInfo":"fn","SetConfig":"fn","GetMaxVoIPNumbers":"fn","GetExistingVoIPNumbers":"fn","X_AVM-DE_GetNumberOfClients":"fn","X_AVM-DE_GetClient":"fn","X_AVM-DE_GetClient2":"fn","X_AVM-DE_SetClient":"fn","X_AVM-DE_SetClient2":"fn","X_AVM-DE_GetClient3":"fn","X_AVM-DE_SetClient3":"fn","X_AVM-DE_GetClients":"fn","X_AVM-DE_GetNumberOfNumbers":"fn","X_AVM-DE_GetNumbers":"fn","X_AVM-DE_DeleteClient":"fn","X_AVM-DE_DialGetConfig":"fn","X_AVM-DE_DialSetConfig":"fn","X_AVM-DE_DialNumber":"fn","X_AVM-DE_DialHangup":"fn","X_AVM-DE_GetPhonePort":"fn","GetVoIPCommonCountryCode":"fn","SetVoIPCommonCountryCode":"fn","GetVoIPEnableCountryCode":"fn","SetVoIPEnableCountryCode":"fn","GetVoIPCommonAreaCode":"fn","SetVoIPCommonAreaCode":"fn","GetVoIPEnableAreaCode":"fn","SetVoIPEnableAreaCode":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Storage:1":{"actions":{"GetInfo":"fn","SetFTPServer":"fn","SetFTPServerWAN":"fn","SetSMBServer":"fn","GetUserInfo":"fn","SetUserConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_OnTel:1":{"actions":{"GetInfo":"fn","SetEnable":"fn","SetConfig":"fn","GetInfoByIndex":"fn","SetEnableByIndex":"fn","SetConfigByIndex":"fn","DeleteByIndex":"fn","GetNumberOfEntries":"fn","GetCallList":"fn","GetPhonebookList":"fn","GetPhonebook":"fn","AddPhonebook":"fn","DeletePhonebook":"fn","GetPhonebookEntry":"fn","SetPhonebookEntry":"fn","DeletePhonebookEntry":"fn","GetDECTHandsetList":"fn","GetDECTHandsetInfo":"fn","SetDECTHandsetPhonebook":"fn","GetNumberOfDeflections":"fn","GetDeflection":"fn","GetDeflections":"fn","SetDeflectionEnable":"fn"}},"urn:dslforum-org:service:X_AVM-DE_WebDAVClient:1":{"actions":{"GetInfo":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_UPnP:1":{"actions":{"GetInfo":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Speedtest:1":{"actions":{"GetInfo":"fn","SetConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_RemoteAccess:1":{"actions":{"GetInfo":"fn","SetConfig":"fn","GetDDNSInfo":"fn","GetDDNSProviders":"fn","SetDDNSConfig":"fn"}},"urn:dslforum-org:service:X_AVM-DE_MyFritz:1":{"actions":{"GetInfo":"fn","GetNumberOfServices":"fn","GetServiceByIndex":"fn","SetServiceByIndex":"fn","DeleteServiceByIndex":"fn"}},"urn:dslforum-org:service:X_AVM-DE_TAM:1":{"actions":{"GetInfo":"fn","SetEnable":"fn","GetMessageList":"fn","MarkMessage":"fn","DeleteMessage":"fn"}},"urn:dslforum-org:service:X_AVM-DE_AppSetup:1":{"actions":{"GetInfo":"fn","GetConfig":"fn","RegisterApp":"fn","SetAppVPN":"fn","SetAppMessageReceiver":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Homeauto:1":{"actions":{"GetGenericDeviceInfos":"fn","GetSpecificDeviceInfos":"fn","SetSwitch":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Homeplug:1":{"actions":{"GetNumberOfDeviceEntries":"fn","GetGenericDeviceEntry":"fn","GetSpecificDeviceEntry":"fn","DeviceDoUpdate":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Dect:1":{"actions":{"GetNumberOfDectEntries":"fn","GetGenericDectEntry":"fn","GetSpecificDectEntry":"fn","DectDoUpdate":"fn"}},"urn:dslforum-org:service:X_AVM-DE_Filelinks:1":{"actions":{"GetNumberOfFilelinkEntries":"fn","GetGenericFilelinkEntry":"fn","GetSpecificFilelinkEntry":"fn","NewFilelinkEntry":"fn","SetFilelinkEntry":"fn","DeleteFilelinkEntry":"fn"}},"urn:dslforum-org:service:WLANConfiguration:1":{"actions":{"SetEnable":"fn","GetInfo":"fn","SetConfig":"fn","SetSecurityKeys":"fn","GetSecurityKeys":"fn","SetDefaultWEPKeyIndex":"fn","GetDefaultWEPKeyIndex":"fn","SetBasBeaconSecurityProperties":"fn","GetBasBeaconSecurityProperties":"fn","GetStatistics":"fn","GetPacketStatistics":"fn","GetBSSID":"fn","GetSSID":"fn","SetSSID":"fn","GetBeaconType":"fn","SetBeaconType":"fn","GetChannelInfo":"fn","SetChannel":"fn","GetBeaconAdvertisement":"fn","SetBeaconAdvertisement":"fn","GetTotalAssociations":"fn","GetGenericAssociatedDeviceInfo":"fn","GetSpecificAssociatedDeviceInfo":"fn","X_SetHighFrequencyBand":"fn","X_AVM-DE_SetStickSurfEnable":"fn","X_AVM-DE_GetIPTVOptimized":"fn","X_AVM-DE_SetIPTVOptimized":"fn","X_AVM-DE_GetNightControl":"fn","X_AVM-DE_GetWLANHybridMode":"fn","X_AVM-DE_SetWLANHybridMode":"fn","X_AVM-DE_GetWLANExtInfo":"fn","X_AVM-DE_GetWPSInfo":"fn","X_AVM-DE_SetWPSConfig":"fn"}},"urn:dslforum-org:service:WLANConfiguration:2":{"actions":{"SetEnable":"fn","GetInfo":"fn","SetConfig":"fn","SetSecurityKeys":"fn","GetSecurityKeys":"fn","SetDefaultWEPKeyIndex":"fn","GetDefaultWEPKeyIndex":"fn","SetBasBeaconSecurityProperties":"fn","GetBasBeaconSecurityProperties":"fn","GetStatistics":"fn","GetPacketStatistics":"fn","GetBSSID":"fn","GetSSID":"fn","SetSSID":"fn","GetBeaconType":"fn","SetBeaconType":"fn","GetChannelInfo":"fn","SetChannel":"fn","GetBeaconAdvertisement":"fn","SetBeaconAdvertisement":"fn","GetTotalAssociations":"fn","GetGenericAssociatedDeviceInfo":"fn","GetSpecificAssociatedDeviceInfo":"fn","X_SetHighFrequencyBand":"fn","X_AVM-DE_SetStickSurfEnable":"fn","X_AVM-DE_GetIPTVOptimized":"fn","X_AVM-DE_SetIPTVOptimized":"fn","X_AVM-DE_GetNightControl":"fn","X_AVM-DE_GetWLANHybridMode":"fn","X_AVM-DE_SetWLANHybridMode":"fn","X_AVM-DE_GetWLANExtInfo":"fn","X_AVM-DE_GetWPSInfo":"fn","X_AVM-DE_SetWPSConfig":"fn"}},"urn:dslforum-org:service:Hosts:1":{"actions":{"GetHostNumberOfEntries":"fn","GetSpecificHostEntry":"fn","GetGenericHostEntry":"fn","X_AVM-DE_GetGenericHostEntryExt":"fn","X_AVM-DE_GetChangeCounter":"fn","X_AVM-DE_SetHostNameByMACAddress":"fn","X_AVM-DE_GetAutoWakeOnLANByMACAddress":"fn","X_AVM-DE_SetAutoWakeOnLANByMACAddress":"fn","X_AVM-DE_WakeOnLANByMACAddress":"fn","X_AVM-DE_GetSpecificHostEntryExt":"fn","X_AVM-DE_HostsCheckUpdate":"fn","X_AVM-DE_HostDoUpdate":"fn"}},"urn:dslforum-org:service:LANEthernetInterfaceConfig:1":{"actions":{"SetEnable":"fn","GetInfo":"fn","GetStatistics":"fn"}},"urn:dslforum-org:service:LANHostConfigManagement:1":{"actions":{"GetInfo":"fn","SetDHCPServerEnable":"fn","SetIPInterface":"fn","GetAddressRange":"fn","SetAddressRange":"fn","GetIPRoutersList":"fn","SetIPRouter":"fn","GetSubnetMask":"fn","SetSubnetMask":"fn","GetDNSServers":"fn","GetIPInterfaceNumberOfEntries":"fn"}},"urn:dslforum-org:service:WANCommonInterfaceConfig:1":{"actions":{"GetCommonLinkProperties":"fn","GetTotalBytesSent":"fn","GetTotalBytesReceived":"fn","GetTotalPacketsSent":"fn","GetTotalPacketsReceived":"fn","X_AVM-DE_SetWANAccessType":"fn","X_AVM-DE_GetOnlineMonitor":"fn"}},"urn:dslforum-org:service:WANDSLInterfaceConfig:1":{"actions":{"GetInfo":"fn","GetStatisticsTotal":"fn"}},"urn:dslforum-org:service:WANDSLLinkConfig:1":{"actions":{"GetInfo":"fn","SetEnable":"fn","GetAutoConfig":"fn","SetDSLLinkType":"fn","GetDSLLinkInfo":"fn","SetDestinationAddress":"fn","GetDestinationAddress":"fn","SetATMEncapsulation":"fn","GetATMEncapsulation":"fn","GetStatistics":"fn"}},"urn:dslforum-org:service:WANEthernetLinkConfig:1":{"actions":{}},"urn:dslforum-org:service:WANPPPConnection:1":{"actions":{"GetInfo":"fn","GetConnectionTypeInfo":"fn","SetConnectionType":"fn","GetStatusInfo":"fn","GetUserName":"fn","SetUserName":"fn","SetPassword":"fn","GetNATRSIPStatus":"fn","SetConnectionTrigger":"fn","ForceTermination":"fn","RequestConnection":"fn","GetGenericPortMappingEntry":"fn","GetSpecificPortMappingEntry":"fn","AddPortMapping":"fn","DeletePortMapping":"fn","GetExternalIPAddress":"fn","X_GetDNSServers":"fn","X_SetDNSServers":"fn","GetLinkLayerMaxBitRates":"fn","GetPortMappingNumberOfEntries":"fn","SetRouteProtocolRx":"fn","SetIdleDisconnectTime":"fn","X_AVM-DE_GetAutoDisconnectTimeSpan":"fn","X_AVM-DE_SetAutoDisconnectTimeSpan":"fn"}},"urn:dslforum-org:service:WANIPConnection:1":{"actions":{"GetInfo":"fn","GetConnectionTypeInfo":"fn","SetConnectionType":"fn","GetStatusInfo":"fn","GetNATRSIPStatus":"fn","SetConnectionTrigger":"fn","ForceTermination":"fn","RequestConnection":"fn","GetGenericPortMappingEntry":"fn","GetSpecificPortMappingEntry":"fn","AddPortMapping":"fn","DeletePortMapping":"fn","GetExternalIPAddress":"fn","X_GetDNSServers":"fn","X_SetDNSServers":"fn","GetPortMappingNumberOfEntries":"fn","SetRouteProtocolRx":"fn","SetIdleDisconnectTime":"fn"}}}

**Comment by soef** [comment]
Thank's for this Information.  I think your fritzbox does not support 5GHz. Therefore the guest wlan functions are in WLANConfiguration:2, wtich normaly contains wlan 5.0 ghz fiúnctions.

please try Version 0.1.29. I think with this Version you can switch your guest wlan state.

**Comment by vore** [comment]
Hello!

Yep, this was the problem. It works with this WLAN. My current Fritzbox 
does not support 5Ghz (I do not  need it). After my 3rd Fritzbox got 
killed due to lightning strikes I bought a cheaper one.

Thanks for your help!

Regards

**Comment by vore** [comment]
Hello!

Thanks.. this was the problem. I works with this WLAN. My current 
Fritzbox does not support 5Ghz WLAN because I do not need it. I had 3 
boxes killed due to lightning strikes I bought a cheaper one without 
5Ghz WLAN.

Thanks again!

Regards

Vore

**Comment by pr0j3ctx** [comment]
Ich möchte kein eigenes Issue dafür aufmachen. Bei mir geht der dumpservices command. 
Aber ich finde keine Möglichkeit die folgenden Informationen abzufragen die dumpservices mir liefert.
Kannst du mir hier helfen?

```
  "urn:dslforum-org:service:WANCommonInterfaceConfig:1": {
    "actions": {
      "GetCommonLinkProperties": "fn",
      "GetTotalBytesSent": "fn",
      "GetTotalBytesReceived": "fn",
      "GetTotalPacketsSent": "fn",
      "GetTotalPacketsReceived": "fn",
      "X_AVM-DE_SetWANAccessType": "fn",
      "X_AVM-DE_GetOnlineMonitor": "fn"
    }
```
