### ISSUE TITLE
Cannot read property 'services' of undefined

### ISSUE THREAD

**Issue by arteck** [soef/ioBroker.tr-064#16]
Fritzbox 7490

`TypeError:	2017-01-15 12:17:18.160	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)

TypeError:	2017-01-15 12:17:18.160	error	at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)

TypeError:	2017-01-15 12:17:18.160	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:228:12)
TypeError:	2017-01-15 12:17:18.160	error	at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:270:10)
TypeError:	2017-01-15 12:17:18.160	error	at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
TypeError:	2017-01-15 12:17:18.160	error	at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:45:30)
TypeError:	2017-01-15 12:17:18.160	error	at Object.that.states.States.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2226:37)
TypeError:	2017-01-15 12:17:18.160	error	at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/soef/soef.js:1062:21)
TypeError:	2017-01-15 12:17:18.160	error	at Object.onStateChange (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:112:27)
TypeError:	2017-01-15 12:17:18.160	error	at TR064.setWLANGuest (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:339:32)
TypeError:	2017-01-15 12:17:18.160	error	Cannot read property 'services' of undefined
message	2017-01-15 12:17:18.133	error	tr-064.0.states.wlanGuest [object Object] Cannot read property 'services' of undefined
tr-064.0	2017-01-15 12:17:11.546	info	starting. Version 0.1.22 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.7.2`

**Comment by soef** [comment]
Hello, can you please update to version 0.1.26. With this version you can create a dump of the available services of your firtzbox. btw. i'm also using a fritzbox 7490 without problems.

To create a dump set the state tr-064.0.states.command to dumpservices. The response will be stored in the state commandResult
