### ISSUE TITLE
Set Guest Wlan Password

### ISSUE THREAD

**Issue by simpixo** [soef/ioBroker.tr-064#17]
Would it be possible to set the password for the guest wlan over this adapter? According to AVM dokumentation its possible to set the wlan passwords over TR-064

Could you implement this function? Because an other user has implement a possibility to generate a password and a QR Code but we have to set it into the fritzbox ;)

That would be really wonderful :-)

**Comment by soef** [comment]
with version 0.1.30 it is possible to set the 2.4, 5.0 and guest wlan Passwords.

**Comment by simpixo** [comment]
Thanks 🙏🏼 that is perfect!
