### ISSUE TITLE
Anrufbeantworter aktivieren/deaktivieren

### ISSUE THREAD

**Issue by AlGu318** [soef/ioBroker.tr-064#18]
Hallo soef,

kann man bei dem Adapter die Funktion "AB einschalten/ausschalten" implementieren? Wenn ich das richtig gesehen habe, ist diese Funktion noch nicht integriert. Aktuell habe ich dafür ein SH-Skript das auf der Shell aufgerufen werden muss und dein Adapter wäre natürlich die smartere Lösung.
Das Skript von mir bekommt die Zahl (Index) des ABs der geändert werden soll und "true/false" fürs de-/aktivieren. Falls dir das hilf, kann ich das Skript gerne schicken.

Vielen Dank und Gruß
AlGu

**Comment by soef** [comment]
Du kannst dafür den tr-064.0.states.command state verwenden. Um z.B. den ersten AB zu deaktivieren musst du das command Feld auf folgenden Wert setzen:

{ "service": "urn:dslforum-org:service:X_AVM-DE_TAM:1", "action": "SetEnable", "params": { "NewIndex": 0, "NewEnable": 0 } }

Die Function wird dann nativ über das AVM-Protokoll aufgerufen, also ohne ein SH Skript. Das Ergebnis, falls es eines gibt, steht dann als JSON in commandResult.

Ich kann die AB Funktion aber bei Zeiten auch einmal nativ implementieren.

Grüße, soef.

**Comment by AlGu318** [comment]
Vielen dank schon mal für die Hilfe. Das aktivieren und deaktivieren klappt, nur leider kommt danach ein Fehler und der Adapter stoppt und startet dann neu. Das Log zeigt folgendes:
host.ioBroker-Pi	2017-01-27 12:42:55.537	info	Restart adapter system.adapter.tr-064.0 because enabled
host.ioBroker-Pi	2017-01-27 12:42:55.537	error	instance system.adapter.tr-064.0 terminated with code 0 (OK)
tr-064.0	2017-01-27 12:42:55.492	info	terminating
tr-064.0	2017-01-27 12:42:55.477	error	at Object.write (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/node_modules/sax/lib/sax.js:1449:13)
tr-064.0	2017-01-27 12:42:55.477	error	at closeTag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
tr-064.0	2017-01-27 12:42:55.477	error	at emitNode (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
tr-064.0	2017-01-27 12:42:55.477	error	at emit (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
tr-064.0	2017-01-27 12:42:55.477	error	at Object.onclosetag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/xml2js.js:447:26)
tr-064.0	2017-01-27 12:42:55.477	error	at Parser.emit (events.js:169:7)
tr-064.0	2017-01-27 12:42:55.477	error	at emitOne (events.js:77:13)
tr-064.0	2017-01-27 12:42:55.477	error	at Parser. (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/xml2js.js:489:18)
tr-064.0	2017-01-27 12:42:55.477	error	at /opt/iobroker/node_modules/iobroker.tr-064/node_modules/tr-O64/lib/Service.js:267:17
tr-064.0	2017-01-27 12:42:55.477	error	at /opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:357:39
tr-064.0	2017-01-27 12:42:55.477	error	TypeError: Cannot read property 'name' of undefined
tr-064.0	2017-01-27 12:42:55.462	error	uncaught exception: Cannot read property 'name' of undefined
tr-064.0	2017-01-27 12:42:55.446	info	{}
tr-064.0	2017-01-27 12:42:44.606	info	starting. Version 0.1.30 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.5.0

Brauchst du noch was um den Fehler nachzuvollziehen?

Gruß AlGu

**Comment by soef** [comment]
Danke für die Info. Ist in 0.1.31 behoben.

**Comment by AlGu318** [comment]
Das ging schnell, habe den Adapter über die Shell aktualisiert und nun gibt's keine Fehlermeldung mehr nach den "command" Aufrufen.

Vielen Dank :-)
