### ISSUE TITLE
FritzFon/DECT Telefon klingeln lassen?

### ISSUE THREAD

**Issue by coyote1** [soef/ioBroker.tr-064#20]
Hallo soef,
Im Homematic Forum gibt es Scripte mit denen man die Fritzbox bedienen kann. Dort ist auch ein Script dabei, mit dem man ein an die FritzBox angeschlossenens DECT Telefon über interne Nummer klingeln lassen kann.
Ist so etwas mit deinem TR-64 Adapter möglich? Ziel ist es bei betätigen der Türklingel auch das FritzFon klingeln zu lassen.

**Comment by soef** [comment]
You can use the command state using the following commands. Set the "tr-064.0.states.command" state to:
{ "service":"urn:dslforum-org:service:X_VoIP:1", "action": "X_AVM-DE_DialNumber", "params": { "NewX_AVM-DE_PhoneNumber": "**610#" }}

To stop the ring use:
{ "service":"urn:dslforum-org:service:X_VoIP:1", "action": "X_AVM-DE_DialHangup", "params": {}}

If I get time, I will implement the call nativ.

**Comment by soef** [comment]
In version 0.1.32 I have implemented a ring state. Parameter is the phonennumer and optional a Duration. 
E.g.: **610, 10

**Comment by coyote1** [comment]
Hmm, danke fürs implementieren. Hab es nur noch nicht hinbekommen.
Wenn ich "ring" auf **610, 10 setze passiert nichts, mache ich was falsch? Muss ich noch was setzen?

Noch ne kleine Frage, man kann doch auch bestimmt über einen command das LiveBild auf dem FritzFon aufrufen oder? Wäre genial, dann könnte ich bei betätigen meiner Klingel, das FritzFon klingeln lassen und das LiveBild anzeigen.

**Comment by soef** [comment]
Hallo, die **610 war nur ein Beispiel. Da musst du deine interne Nummer des Telefons einsetzen. Die Nummer findest du in den Einstellungen der "Telefoniergeräte". Zu dem LiveBild des FritzFon kann ich leider nichts sagen. Viele Grüße.

**Comment by coyote1** [comment]
Ja, das war mir bewusst. Meine interne Nummer ist auch die **610 , aber wenn ich den Datenpunkt "ring"  direkt unter Objekte damit beschreibe, passiert nichts.

**Comment by soef** [comment]
Welche Fritzbox hast du im Einsatz?
Klingelt das Telefon denn, wenn du folgendes (inklusive der geschweiften Klammern) in den command Datenpunkt schreibst?
{ "service":"urn:dslforum-org:service:X_VoIP:1", "action": "X_AVM-DE_DialNumber", "params": { "NewX_AVM-DE_PhoneNumber": "**610" }}

Ansonsten kannst du einmal dumpservices in den command Datenpunkt schreiben. Das Ergebnis steht dann im Datenpunkt commandResult. Das bitte hier einmal posten.

**Comment by coyote1** [comment]
Ich habe eine 6490 Kabel Box, aber eine freie und nicht vom Kabel Anbieter.
Hatte ich direkt versucht als du es geschrieben hattest im zweiten Post, hatte nicht funktioniert.
OK, das teste ich gleich mal und poste das Ergebnis

**Comment by soef** [comment]
Der Service zum Wählen einer Nummer wird auf jeden Fall von deiner FritzBox angeboten. Warum es bei dir nun nicht funktioniert, kann ich so nicht sagen. Funktioniert denn der Test-Button in den FritzBox-Einstellungen für das Telefon bzw. Nebenstelle?

**Comment by coyote1** [comment]
Ja, über Testen funktioniert es. Bin ein Stück weiter. Wenn ich die interne Rufnummer **620(Smartphone mit FritzFon App) eingebe klingelt mein Smartphone und zeigt einen internen Anruf von **610 an.
Leider kann ich die interne Rufnummer nicht manuell ändern.

Scheint, als würde über den Befehl mit **610 der Ein und Ausgehende Anruf gleich sein und das funktioniert dann nicht. Kann das sein?

**Comment by soef** [comment]
Kannst Du dann nicht die interne Nummer der Nebenstelle auf z.B. **621 ändern?

**Comment by coyote1** [comment]
Leider geht genau das nicht. Interne Nummern kann man nicht ändern.

**Comment by soef** [comment]
Hallo, du kannst aber ein neues Telefon mit den Daten des jetzigen anlegen und das aktuelle (**610) entfernen.

**Comment by coyote1** [comment]
Genau, ich habe einfach erst ein anderes Mobilteil angemeldet und dann das FritzFon. Hat dann die **0611 bekommen. Funktioniert auch jetzt soweit, nur seltsamerweise funktioniert das andere Mobilteil jetzt auch mit der **0610.
Vielen Dank nochmal für deine Hilfe und den Adapter
