### ISSUE TITLE
Anrufer Bilder 

### ISSUE THREAD

**Issue by bahnuhr** [soef/ioBroker.tr-064#22]
Guten Abend,

in der Fritzbox sind ja auch die Anrufer Bilder gespeichert.

Kann man auf diese irgendwie zugreifen.

mfg
Dieter

**Comment by bahnuhr** [comment]
Naja,
ne Antwort wäre schon gut gewesen.
Scheint wohl nicht zu gehen.
mfg

**Comment by soef** [comment]
Hallo, sorry, bin noch nicht dazu genkommen. Es stimmt aber, hab' vergessen hier etwas dazu zu schreiben. Ich schaue die nächsten Tage einmal was da geht...

Grüße...

**Comment by soef** [comment]
Hallo, habe etwas gefunden. Zumindest kannst du die Image-URL eines Telefonbucheintrages von einem Namen oder einer Telefonnummer bekommen. Erklärung steht in der readme auf github.

Installieren kannst due die Vorabversion aus dem ioBroker Rootverzeichnis wie folgt?
npm install iobroker.tr-064@dev
iobroker upload tr-064

Grüße

**Comment by bahnuhr** [comment]
Hallo,
die Installation klappt nicht.
Sowohl direkt im Verzeichnis als auch unter iobroker (dann github) klappt es nicht. Ich bekomme lauter Fehlermeldungen.
Eine Erklärung in readme kann ich auch nicht finden.
mfg
Dieter

**Comment by soef** [comment]
Hallo, die Erklärung (bisher nur auf github) ist in der readme im Abschnitt "Phonebook".
Welches Betriebssystem verwendest du? Mit Linux wäre das ioBroker Root-Verzeichnis /opt/iobroker/.

**Comment by bahnuhr** [comment]
Hallo, ich benutze win7.
Bin in den Ordner: c:/iobroker und dann o.g. Link.
Klappt aber nicht.
Mit freundlichen Grüßen
Dieter

**Comment by bahnuhr** [comment]
Erklärung bei phonebook hab ich gefunden.
Jetzt muss ich nur die neue version installiert bekommen.
Schaun wir mal.

**Comment by soef** [comment]
Hallo, oh, Windows 7 habe ich nicht mehr. Ich denke aber daran liegt es nicht. Welche node.js Version verwendest du?

PS.: Warum hast Du eigentlich nicht die kostenlose Update-Möglichkeit von Microsoft genutzt um auf Windows 10 zu gelangen?

**Comment by bahnuhr** [comment]
node 6.9

Update auf win10: hab ich irgendwie nicht mitbekommen.

**Comment by bahnuhr** [comment]
hat irgendwie geklappt (glaub ich) trotz fehlermeldungen.
angezeigt bekomme ich nun bei den adaptern Vers. 0.3.3
Diese installiert und dann bei den instanzen die werte eingegeben.
Komischerweise wirde die instanz nicht grün.

Irgendeine Idee ? (hat die Installation doch nicht geklappt ?)

**Comment by bahnuhr** [comment]
Zwischenmeldung.
Instanz jetzt grün.
Und ich sehe auch unter den Objekten "Image URL".
Jetzt muss ich mal damit ein bisschen testen.

Danke bis hierhin.
mfg
Dieter

**Comment by bahnuhr** [comment]
so getestet.
Instanz ist grün.
Jedoch wird bei mir beim "callername" nichts angezeigt sowie bei allen 3 unter Phonebook (name, nummer, image url) wird ebenfalls nichts angezeigt.

Was mach ich denn falsch ?

**Comment by soef** [comment]
Hallo, gibt es denn einen Telefonbucheintrag für die anrufende Nummer?

**Comment by bahnuhr** [comment]
Hallo,
na klar.
Hat ja mit der alten Version einwandfrei geklappt. Habe mir sogar extra ein iobroker script zur Weiterverarbeitung (Nachricht an telegram, etc.) geschrieben.

Klappt halt jetzt nicht mehr.

**Comment by bahnuhr** [comment]
so,
ich habs jetzt mal mit mehreren Handys probiert. Handy Nr. ist im Telefonbuch vorhanden. Mit der alten Version hat es geklappt.
Mit der neuen Version funktioniert dies nicht mehr.
Wie oben erwähnt erscheint nichts mehr bei callername sowie im phonebook.

Hängt es mit dem update der Fritzbox auf 6.80 zusammen ?

**Comment by bahnuhr** [comment]
deinstalliert und installiert.
Jetzt wird wieder ...inbound.callername angezeigt.
Bei phonebook (alle 3) steht jedoch gar nichts.

**Comment by bahnuhr** [comment]
so soef; ich bin ein Stück weiter.
wenn ich bei phonebook.number manuell etwas eintrage, dann wird bei imageurl etwas eingetragen.
In diesem Fall wird versucht ein download von google zu holen. klappt aber nicht.
Der Eintrag bei imageurl wäre:
http://192.168.xxx.1:49000/download.lua?path=https://www.google.com/m8/feeds/photos/media/d.xxxxxx%40googlemail.com/xxxxxx&sid=xxxxxx&pbid=240
(habe teilweise xxx gesetzt).
Wie bekomme ich nun dies angezeigt.

Wenn du dies hinbekommst wäre das super klasse.

mfg
Dieter

**Comment by soef** [comment]
Hallo, absolute Image-Pfade werden nun unverändert verwendet. Habe es leider nicht Detail prüfen können.

**Comment by bahnuhr** [comment]
Guten Morgen,
was heißt das nun?
Muss ich nochmal update machen. Oder geht es (noch) nicht?
mfg

**Comment by bahnuhr** [comment]
Habe mal ein bisschen getestet:
1. Telefonbuch in Fritzbox manuell angelegt.
- Da kann man einen Eintrag anlegen und dann auch ein Bild hinterlegen.
- Bei Eintrag in Phonebook dieser Tel.Nr. wird url angezeigt. 
- Diese url in ein image eintragen und Bild wird angezeigt.
- Funktioniert
2. Telefonbuch von google in Fritzbox einlesen.
- In Fritzbox wird kein Bild angezeigt; jedoch wird das bild-symbol vor dem Namen angezeigt.
- Bei Eintrag in Phonebook dieser Tel.Nr. wird url angezeigt. 
http://192.168.xxx.1:49000/download.lua?path=https://www.google.com/m8/feeds/photos/media/d.xxxxxx%40googlemail.com/xxxxxx&sid=xxxxxx&pbid=240
- Diese url in ein image eintragen und Bild wird nicht !!! angezeigt.

2a. Ermitteln der Bild url direkt aus google Kontakte.
- Wenn man in google auf das bild geht, kommt folgende url:
https://plus.google.com/u/0/_/focus/photos/private/xxxxxxxxxxxxxxx-xxxxxxxxxxx?sz=96
(teilweise wieder xxx eingetragen).
- Diese url in ein image eintragen und Bild wird nicht !!! angezeigt.

Fazit:
- Manuelle Bilder in Fritzbox geht.
- Bilder von google Kontakte geht nicht. Irgendwie passt die url nicht ?!?!?!

mfg
Dieter

**Comment by soef** [comment]
Hallo, für externe Telefonbücher sollte mit der Version 0.3.6 nun auch die richtige imageurl eingesetzt werden. Schaue doch einmal, wie es bei dir aussieht.

Grüße.

**Comment by bahnuhr** [comment]
Danke.
Ich probiers aus und melde mich dann wieder.
mfg

**Comment by bahnuhr** [comment]
ok soef,
hab es eben probiert. Bei mir klappt es nicht.
Genau wie oben schon beschrieben:
Es kommt:
http://192.168.xxx.1:49000/download.lua?path=https://www.google.com/m8/feeds/photos/media/d.xxxxxx%40googlemail.com/xxxxxx&sid=xxxxxx&pbid=240
Diese url in ein image eintragen und Bild wird nicht !!! angezeigt.

fg

**Comment by soef** [comment]
Oh man, schwere Geburt...
Versuche es noch einmal mit der Version 0.3.7
Grüße.

**Comment by bahnuhr** [comment]
Hallo soef,
erstmal danke, dass du an dem Thema so dran bleibst.
ich versuche es sofort.
mfg
Dieter

**Comment by bahnuhr** [comment]
tut mir leid soef,
es geht nicht.
- Adapter steht nun auf 0.3.7
- Instanz gelöscht und wieder neu installiert.
- Nr. bei phonebook eingegeben.
- bei image url teht die gleiche url wie oben
- url im browser eingegeben: Fehler von google 401
- url in ein image eingetragen; Bild kommt nicht!

mfg
Dieter

**Comment by bahnuhr** [comment]
Hallo soef,
ich hab mal ein bisschen gegoogelt.
Brauch ich um auf die Bilder zu zugreifen eine "google contacts api" ?

mfg
Dieter

**Comment by soef** [comment]
Hallo, ich glaube das geht so gar nicht. Vielleicht mit der Google API. -
Selbst die AVM Fritz Fon App kann die Fotos zu den Kontakten von Google nicht anzeigen. Dort wird sowohl bei iOS als auch auf Android Geräten nur ein Platzhalter angezeigt.

**Comment by bahnuhr** [comment]
Aber das Fritz for Telefon ca zeigt die bilder an. Also muss es doch irgendwie gehen.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.

Am 07.03.2017, 21:11, Soef <notifications@github.com> schrieb:

Hallo, ich glaube das geht so gar nicht. Vielleicht mit der Google API. -
Selbst die AVM Fritz Fon App kann die Fotos zu den Kontakten von Google nicht anzeigen. Dort wird sowohl bei iOS als auch auf Android Geräten nur ein Platzhalter angezeigt.

**Comment by soef** [comment]
Das stimmt. Wenn das C4 die Fotos anzeigt, muss es irgendwie gehen. Ich weiß aktuell aber nicht wie. Du kannst ja mit die imageurl einmal zerlegen und etwas experimentieren.

**Comment by soef** [comment]
die -> der

**Comment by bahnuhr** [comment]
Kann man dendatenverkehr mit dem Handy irgendwie auslesen?
Mit der URL hab ich schon hinein her experimentiert. Habs noch nicht hin bekommen. 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.

Am 08.03.2017, 13:18, Soef <notifications@github.com> schrieb:

Das stimmt. Wenn das C4 die Fotos anzeigt, muss es irgendwie gehen. Ich weiß aktuell aber nicht wie. Du kannst ja mit die imageurl einmal zerlegen und etwas experimentieren.

**Comment by soef** [comment]
Wenn du Zeit hast, schau mal auf deiner FritzBox hier: http://fritz.box/support.lua
-> Paketmitschnitt
wireshark hilft dir beim analysieren...

**Comment by bahnuhr** [comment]
Geht wireshark auch für DECT ?
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.

Am 08.03.2017, 22:16, Soef <notifications@github.com> schrieb:

Wenn du Zeit hast, schau mal auf deiner FritzBox hier: http://fritz.box/support.lua
-> Paketmitschnitt
wireshark hilft dir beim analysieren...

**Comment by soef** [comment]
Hallo, ich denke Wireshark kann auhc das DECT Protokoll anzeigen.

**Comment by bahnuhr** [comment]
In dieser support Datei sind die gleichen "https:...." wie in deinem Datenpunkt ausgelesen wird.
Irgendwie fehlt da noch was. Denn nur dieser Befehl zeigt das Bild nicht an.

Kennst du dich damit aus ?
Oder müssen wir jetzt hier Schluss machen, weil es irgendwie nicht geht wie wir uns das vorstellen ?

mfg
Dieter

**Comment by soef** [comment]
Ich weiß aktuell nicht wie die URL zum Funktionieren zu bringen ist. Werde aber die Augen auf halten und ggf. später etwas anpassen.

**Comment by bahnuhr** [comment]
Danke im Voraus.
Bis dann.
