### ISSUE TITLE
Fritzbox 7490 Verbindung nicht möglich

### ISSUE THREAD

**Issue by mctom** [soef/ioBroker.tr-064#24]
Hallo,

ich habe bei unter ioBroker auch den Adapter installiert.
Leider bekomme ich folgende Fehlermeldung beim Start:

tr-064.1	2017-02-22 22:14:11.077	error	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
tr-064.1	2017-02-22 22:14:11.077	error	at exports._exceptionWithHostPort (util.js:930:20)
tr-064.1	2017-02-22 22:14:11.077	error	at Object.exports._errnoException (util.js:907:11)
tr-064.1	2017-02-22 22:14:11.077	error	Error: connect ECONNREFUSED 192.168.2.5:1012
tr-064.1	2017-02-22 22:14:11.076	error	uncaught exception: connect ECONNREFUSED 192.168.2.5:1012

Woran kann dies liegen ?

Die Besonderheit bei mir ist, dass ich den Adapter 2x installiert habe, da ich 2 Fritzboxen in meinem Netz betreibe. Kann es damit zu tun haben.

Gruß

Michael

**Comment by soef** [comment]
Hallo,

versuche einmal in den Einstellungen der Instanz die IP der entsprechenden FritzBox einzutragen. Als default ist dort "fritz.box" eingetragen.

Gruß

**Comment by mctom** [comment]
Hi,

habe es auch schon mit der IP probiert. Auch dann leider kein Erfolg.

Gruß

Michael

**Comment by soef** [comment]
Hallo, ah, sehe jetzt erst, das es sich um Port 1012 handelt. Der ist für den Anrufmonitor und muss auf der Fritzbox freigeschaltet werden. Oder aber du schaltest in den Einstellungen den Callmonitor aus.

Zum Freischalten bei Google einfach nach: fritzbox 1012 freischalten suchen.
