### ISSUE TITLE
State externalP leer

### ISSUE THREAD

**Issue by Photographix** [soef/ioBroker.tr-064#26]
Hallo, ich weiss nicht ob dies ein Bug ist aber der Datenpunk "externalP" ist bei mir leer. Auch scheint reconnect nicht zu gehen wenn ich den State auf "true" setze. Er bleibt dann auch ewig auf true. Gast Wlan geht aber an/aus.

Fritzbox 7490, FritzOS 6.80, TR-64 Adapter 0.3.6, ioBroker unter Windows 10, Admin 1.6.12, js-controller 0.16.1, Fritzbox als IP im Adapter eingetragen.

LG

**Comment by bahnuhr** [comment]
Ich habe die gleiche Hard- und Software:
FB 7490 mit 6.80, TR 0.3.7 aber Win7

Bei mir funktioniert der Punkt "externalIP".
Es steht dort: 93.181.....

mfg

**Comment by soef** [comment]
Hallo, in der Regel funktioniert der Datenpunkt. Auch bei mir. Ich habe auch eine 7490 und eine 7580. 
Hast Du IPv6 aktiviert? Oder sonst etwas in den Einstellungen verändert? 

Grüße.

**Comment by Photographix** [comment]
Hallo soef, nein IPv6 habe ich nicht an. Ansonsten auch ein "normaler" DSL bei der Telekom. Kein Lite.

**Comment by soef** [comment]
Schau einmal im FritzBox Webinterface unter Heimnetzt -> Heimnetzübersicht / Heimnetzfreigaben ob die beiden oberen Schalter gesetzt sind. Ansonsten könnte es noch an den Rechten des verwendeten User liegen.

**Comment by Photographix** [comment]
Danke hat geholfen uPNP war nicht an. Sondern nur TR-064. Wusste nicht das dies auch gebraucht wird.
