### ISSUE TITLE
I can't enter in the setup login

### ISSUE THREAD

**Issue by stefanoklett** [soef/ioBroker.tr-064#27]
I installed the plugin, but I can't edit the configs:

![2017-03-06 21_49_45-iobroker admin](https://cloud.githubusercontent.com/assets/2768025/23629261/707c29ce-02b7-11e7-95f2-43f822c9128e.png)

regards
Stefano

**Comment by soef** [comment]
Hello, witch version are you using? How do you install the Adapter? 
If you install the adapter manually, you have to update the configuration. you cann do this with the command 
iobroker upload tr-064 
in the ioBroker root Directory

greetings.

**Comment by stefanoklett** [comment]
I try uninstall and re-install manually:
npm install tr-064 --production --prefix "/volume1/opt/iobroker"    
./iobroker add tr-064
./iobroker upload tr-064

But the result is the same.
Is the only plungin I'm using with this problem.
May is working, but I can't configure them.

regards
Stefano

**Comment by soef** [comment]
The config dialog is usig new functions for the datagrid. Therefor  you have to update your iobroker.admin adapter.

**Comment by stefanoklett** [comment]
Many tnks, it works now.

Now I have to find out if (and how) can I ring a phone.

regards
Stefano

**Comment by soef** [comment]
Hello, fine, that it runs now. In a newer Version, I have implemented an error message, if an installation ist using an older ioBroker.admin Adapter.

To let a phone ring, set the state "tr-064.0.states.ring" to a number. If you set it to en internal phonenumber (e.g. **610) this phone will ring. If you set it to an external number the FritzBox will call the external number and your default local phone will ring, if the extern phone will be picked up. (Connect oder Dialhelp)

**Comment by stefanoklett** [comment]
Yes, it works, but if I call the **610 doesn't works, may because is the default phone (how to set up the default phone?). 
It will be possible to ring from a specific number, so that I can set a special bell?
I want to use them as doorbell..

regards
Stefano

**Comment by soef** [comment]
Hello, **610 ist the first internal phonenumber. I only have a german FritzBox. 
You can see the configuration of the telefon devices at: Telefonie (3rd in the left menue) -> Telefongeräte (last bud one in the sub menue)

To configure the device witch is called when a connect to an external number is required: Telefonie (3rd in the left menue) -> Anrufe (1st in the Sub menue) -> Wählhilfe (2nd tap on the top right site)

I hope you can follow the discription.

greetings.

**Comment by stefanoklett** [comment]
I confirm, it works well, many tnks

Stefano
