### ISSUE TITLE
callerName values

### ISSUE THREAD

**Issue by EvilEls** [soef/ioBroker.tr-064#33]
Hi!

When I get a call from a 
*.caller
who is in my FritzBox phonebook,
*.callerName
values are set to the correct Name from the phonebook.

If then another call rings in from a
*.caller
who is NOT in my FritzBox phonebook,
*.callerName
values are not removed and keep the 
*.callerName 
from the call before.

Example:
Fritzbox phonebook:
MSISDN | NAME
012345678910 | Skeletor

First call from "012345678910": <- MSISDN is in phonebook
- all *.caller values are set to "012345678910"
- all *.callerName values are set to "Skeletor"

Second call from "01987654321": <- MSISDN is NOT in phonebook
- all *.caller values are set to "01987654321"
- all *.callerName values KEEP "Skeletor" (but should become "")

io.Broker keeps me thinking a friend is calling, but it's just his evil twin (He-Man) on the phone :-(

**Comment by soef** [comment]
Thanks for this info. Should be fixed in Version 0.3.18
