### ISSUE TITLE
Aktiv-Erkennung von Geräten

### ISSUE THREAD

**Issue by SMundt** [soef/ioBroker.tr-064#34]
Hallo, 

ich habe im Adapter zwei Geräte aktiviert, dessen aktiver Status geprüft werden soll.
Problem ist, dass beide Geräte immer auf active = true stehen, obwohl eins davon sich definitiv nicht im WLAN befindet, da es im anderen Ort unterwegs ist.

Es handelt sich hierbei um zwei Samsung Galaxy S7 Handys.
Ich würde das gern als Anwesenheitserkennung nutzen.

Eine Idee, woran das liegen kann?

**Comment by soef** [comment]
Hallo, bleibt der Status dauerhaft auf "aktiv"? Wie wird das Gerät denn in der FritzBox-Website angezeigt?

**Comment by SMundt** [comment]
Ja bleibt dauerhaft Aktiv obwohl es in der Fritzbox WLAN Übersicht als "nicht verbunden" drin steht.

**Comment by soef** [comment]
Hallo, hast du in der Konfiguration einen Poll Intervall eingestellt? In dem eingestallten Poll Intervall fragt der Adapter den Status bei der FritzBox ab.

**Comment by SMundt** [comment]
Ja, sind 10 Sekunden drin. Im Log sehe ich auch das der Adapter "was macht".
Mir ist aber was aufgefallen. In der FritzBox ist trotz deaktiviertem WLAN im Handy das Telefon unter "Heimnetz" noch aufgeführt. Unter WLAN ->Funknetz auch, allerdings mit dem Status "Nicht verbunden".
Daher meine Frage jetzt, geht der Adapter nach dem Status unter Heimnetz oder nach dem Status unter WLAN -> Funknetz?

**Comment by SMundt** [comment]
Nochmal ich :)
Ich glaube das war jetzt ein Denkfehler meinerseits.
Es scheint doch alles zu funktionieren.
Kann es sein, dass Active durch die Fritzbox erst nach ca. 5 Minuten nach WLAN-Deaktivierung am Endgerät auf "false" gesetzt wird, bzw. die Fritzbox so lange braucht um den "Nicht verbunden" Status zu erkennen?

**Comment by soef** [comment]
Ja, manchmal verhält die FritzBox sich merkwürdig. Wenn MDNS aktiviert ist funktioniert der andere Fall - als das Erkennen des Aktiv-Zustands sofort.

**Comment by SMundt** [comment]
Stimmt. MDNS ist aktiv.
Also wenn WLAN ausgeschaltet wird dauert es ca. 5 Minuten bis Active = false
Wenn WLAN eingeschaltet wird, dann maximal 3 Sekunden bis Active = true

Also möchte ich nochmal festhalten das es KEIN Fehler des Adapters ist, mich bei Dir für Deine Hilfe bedanken und dieses Thema schließen :)
