### ISSUE TITLE
Kein Update des Device-Status

### ISSUE THREAD

**Issue by dabbeljuh22** [soef/ioBroker.tr-064#36]
Leider erfolgt in der Version 0.3.19 kein Update meiner Devices. In Version 0.3.17 entsteht zusätzlich noch ein Error 500. Nähere Infos auch hier: http://forum.iobroker.net/viewtopic.php?f=20&t=7107&p=75404#p75404

Beste Grüße
dabbeljuh

**Comment by soef** [comment]
Verwende einmal die Version 0.3.21. Ist im Moment nur auf github oder per 
npm install iobroker.tr-064@dev
zu installieren.

Grüße, soef.

**Comment by dabbeljuh22** [comment]
Hi, danke für die Mühe. Leider wird es damit auch nicht besser. Wenn du möchtest, kann ich dir gerne weitere Details zu Konfiguration etc. zukommen lassen. Sag mir einfach Bescheid, ob und was nötig ist.

Grundsätzlich sieht es so aus: ioBroker und Komponenten auf dem neusten Stand. Node in Version 6.10.3. Deinen Adapter wie oben installiert und instanziiert. Auf der Fritzbox hab ich einen Benutzer eigens dafür angelegt und mit PW versehen (und den Login auch auf Benutzer/PW geändert).

Wenn ich die Adapterinstanz im Debug-Modus starte, wird das ordentlich im Log protokolliert. Was mich wundert: Ich habe noch keinen Benutzer in die Maske eingegeben, dennoch kann ich bereits Geräte suchen. Diese werden auch lt. Log gefunden und tauchen auch unter Objekte auf. Dürfte das nicht erst nach Eingabe von Benutzer/PW in der Maske passieren!?

Wie auch immer. Nach erstmaligem Erfassen der Geräte wird der Status wie gehabt nicht mehr aktualisiert. Auch im Logfile erscheinen immer nur die 8 Meldungen (redis publish io.system.adapter.tr-064.0.alive ...)

Beste Grüße

**Comment by soef** [comment]
Hallo, hast Du wirklich die Version 0.3.21 installiert? Bei npm ist sie vorerst nur unter dem dev tag verfügbar. Also von github installieren, oder per 
npm install iobroker.tr-064@dev

Grüße

**Comment by dabbeljuh22** [comment]
Hi, ich hab die Version über deinen Konsolenbefehl durchgeführt. Vorher hab ich die Instanz gelöscht und nach der Adapterintallation auch gleich über die Konsole wieder angelegt. Im Browser wird mir im ioBroker-Admin auch 0.3.21 als installiert angezeigt. Kann es trotzdem noch irgendwie ein Problem mit Caching oder so geben? Woran könnte ich im Log sehen, ob etwas daneben geht oder was für dich hilfreich sein könnte?

Ich bin programmiermäßig nicht ganz unbedarft, wenn ich dahingehend was unterstützend tun kann, lass es mich einfach wissen.

Wie gesagt, was mich wundert, dass die Geräte im ersten Step sogar ohne User ausgelesen werden können und danach aber kein Update mehr erfolgt. Ein Neustart der Instanz bringt dann aber wieder aktuelle Ergebnisse.

**Comment by soef** [comment]
Hallo, hast Du auf dem Instanzen Tab in der Spalte "Log Stufe" die Einstellung für den tr-064 Adapter einmal auf Debug gestellt? Die Spalte ist nur im Admin-Modus sichtbar. Dazu oben link auf das Männchen klicken. Dann im Log einmal nach Ausgaben von tr-064 schauen.

Wenn in der Konfiguration noch Geräte eingetragen sind, werden diese auch als Geräte-Objekte angelegt. Auch wird ist für einige (unkritische) tr-064 Funktionen keine Anmeldung notwendig.

Grüße, soef.

**Comment by dabbeljuh22** [comment]
Hallo! Ja, die Log-Stufe hab ich schon die ganze Zeit auf Debug stehen. Nur leider habe ICH da nichts Auffälliges herauslesen kennen. ;-) Ich hab das auch Ausschnittsweise schon in dem o.g. Thread im ioBroker-Forum verlinkt. Helfen dir bestimmte Zeilen weiter? Dann poste ich dir die selbstverständlich.

Ok, das mit der Anmeldung versteh ich. Aber leider kann ich z.B. auch das Gast-Wlan (was mir in inaktivem Zustand mit "true" angezeigt wird) nicht schalten. In meinem Test auf dem parallel noch vorhandenen FHEM hat das vorgestern funktioniert (korrekte Anzeige + Schalten). Bitte nicht als Kritik verstehen, soll nur als Hinweis dienen, um eventuell dem Problem besser auf die Spur zu kommen.

Ich kann doch beim Anlegen der Instanz echt nicht so viel falsch machen ... :-(

Viele Grüße
dabbeljuh
