### ISSUE TITLE
Bitte neue Version freigeben

### ISSUE THREAD

**Issue by Haeusele** [soef/ioBroker.tr-064#38]
Hallo,

mit den aktuellen Sourcen (0.3.22) klappt die Verbindung zur FritzBox wieder. Mit aktuell releaseten Version (0.3.19) kommt immer ein Fehler.

http://forum.iobroker.net/viewtopic.php?f=22&t=4628&start=40

Vielen Dank ! :)

**Comment by Apollon77** [comment]
Und am besten auch im stable aktualisieren für die die irgendwie was komisches  bekommen haben

**Comment by soef** [comment]
Ok, done.
