### ISSUE TITLE
Issue Error: sendSOAPActionRequest Error seems not be fixed

### ISSUE THREAD

**Issue by tomohnejerry** [soef/ioBroker.tr-064#39]
![bildschirmfoto 2017-09-20 um 12 05 29](https://user-images.githubusercontent.com/25080076/30638689-82aa4e42-9dfc-11e7-8ca3-3feb80b52a25.png)
![bildschirmfoto 2017-09-20 um 12 11 19](https://user-images.githubusercontent.com/25080076/30638795-e9c432f0-9dfc-11e7-8ead-32d1699f86c7.png)

**Comment by soef** [comment]
Hi, is the error sill there after a restart of your FritzBox? When does the error appear? At adapter startup or if you do an action?

**Comment by tomohnejerry** [comment]
After restarting my Fritz!Box the issue seems to be solved. Thanks for support (:
