### ISSUE TITLE
Cache "Devicelist" for a certain time when configuring more devices

### ISSUE THREAD

**Issue by Apollon77** [soef/iobroker.tr-064#4]
When configuring devices then each time "find a device" is clicked a new request is done to the Fritzbox, which can be much traffic. But the devicelist do not update that often, so it could be cached for some time (60 seoconds, longer)

**Comment by soef** [comment]
The devicelist is cached (and will be updated during runtime) until the next start of this adapter. I think you are saving and closing the config dialog. Taht results in a restart of the Adapter. Try to add all desired devices and then save and Close.

If it dose not work, let me now
