### ISSUE TITLE
Guest WLAN Zustand wird nicht aktualisiert

### ISSUE THREAD

**Issue by Matten-Matten** [soef/ioBroker.tr-064#42]
Der Zustand vom Gast-WLAN wird nicht aktualisiert. (bei FB 7490 / FRITZ!OS:06.60)

![iobroker admin-07 10 2017_11_04_44](https://user-images.githubusercontent.com/32074970/31306402-e75f7136-ab4f-11e7-9e88-fc5e9c298e4e.png)

**Comment by soef** [comment]
Hallo, der Zustand der wlanxxx wird nur aktualisiert, wenn in der Konfiguration ein Poll Intervall angegeben ist.

**Comment by Matten-Matten** [comment]
![iobroker admin-09 10 2017_14_19_07](https://user-images.githubusercontent.com/32074970/31337780-20013444-acfd-11e7-8269-02682ccd3e25.png)
Ist ja eingestellt.

**Comment by Matten-Matten** [comment]
Hab auch den Poll größer und kleiner gesetzt

**Comment by Matten-Matten** [comment]
Ich habe jetzt auf das aktuelle FritzOS aktualisiert. jetzt funktioniert es.

**Comment by soef** [comment]
Das ist schön. Vielleicht hätte auch ein Neustart der FritzBox zum Erfolg geführt.
