### ISSUE TITLE
Version 0.4.0 startet nicht.

### ISSUE THREAD

**Issue by Matzebhv** [soef/ioBroker.tr-064#43]
Habe gestern das angebotene Update auf 0.4.0 durchgeführt. Der Adapter startet danach nicht mehr bzw. beendet sich ständig selbst.
Aus dem Log:

host.raspberrypi2017-10-08 22:06:33.098errorinstance system.adapter.tr-064.0 terminated with code 0 (OK)Caught2017-10-08 22:06:33.098errorby controller[0]: at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)Caught2017-10-08 22:06:33.098errorby controller[0]: at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)Caught2017-10-08 22:06:33.098errorby controller[0]: at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)Caught2017-10-08 22:06:33.097errorby controller[0]: at Object.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)Caught2017-10-08 22:06:33.096errorby controller[0]: at Parser.emit (events.js:188:7)Caught2017-10-08 22:06:33.091errorby controller[0]: at emitOne (events.js:96:13)Caught2017-10-08 22:06:33.091errorby controller[0]: at Parser. (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)Caught2017-10-08 22:06:33.091errorby controller[0]: at /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17Caught2017-10-08 22:06:33.091errorby controller[0]: at arguments.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:70:22)Caught2017-10-08 22:06:33.091errorby controller[0]: at /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:148:43Caught2017-10-08 22:06:33.090errorby controller[0]: TypeError: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:33.048infoterminatingtr-064.02017-10-08 22:06:33.019errorat closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)tr-064.02017-10-08 22:06:33.019errorat emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)tr-064.02017-10-08 22:06:33.019errorat emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)tr-064.02017-10-08 22:06:33.019errorat Object.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)tr-064.02017-10-08 22:06:33.019errorat Parser.emit (events.js:188:7)tr-064.02017-10-08 22:06:33.019errorat emitOne (events.js:96:13)tr-064.02017-10-08 22:06:33.019errorat Parser. (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)tr-064.02017-10-08 22:06:33.019errorat /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17tr-064.02017-10-08 22:06:33.019errorat arguments.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:70:22)tr-064.02017-10-08 22:06:33.019errorat /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:148:43tr-064.02017-10-08 22:06:33.019errorTypeError: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:33.016erroruncaught exception: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:29.791infostarting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.tr-064, node: v6.11.3 | host.raspberrypi2017-10-08 22:06:33.098errorinstance system.adapter.tr-064.0 terminated with code 0 (OK)Caught2017-10-08 22:06:33.098errorby controller[0]: at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)Caught2017-10-08 22:06:33.098errorby controller[0]: at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)Caught2017-10-08 22:06:33.098errorby controller[0]: at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)Caught2017-10-08 22:06:33.097errorby controller[0]: at Object.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)Caught2017-10-08 22:06:33.096errorby controller[0]: at Parser.emit (events.js:188:7)Caught2017-10-08 22:06:33.091errorby controller[0]: at emitOne (events.js:96:13)Caught2017-10-08 22:06:33.091errorby controller[0]: at Parser. (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)Caught2017-10-08 22:06:33.091errorby controller[0]: at /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17Caught2017-10-08 22:06:33.091errorby controller[0]: at arguments.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:70:22)Caught2017-10-08 22:06:33.091errorby controller[0]: at /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:148:43Caught2017-10-08 22:06:33.090errorby controller[0]: TypeError: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:33.048infoterminatingtr-064.02017-10-08 22:06:33.019errorat closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)tr-064.02017-10-08 22:06:33.019errorat emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)tr-064.02017-10-08 22:06:33.019errorat emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)tr-064.02017-10-08 22:06:33.019errorat Object.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)tr-064.02017-10-08 22:06:33.019errorat Parser.emit (events.js:188:7)tr-064.02017-10-08 22:06:33.019errorat emitOne (events.js:96:13)tr-064.02017-10-08 22:06:33.019errorat Parser. (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)tr-064.02017-10-08 22:06:33.019errorat /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17tr-064.02017-10-08 22:06:33.019errorat arguments.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:70:22)tr-064.02017-10-08 22:06:33.019errorat /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:148:43tr-064.02017-10-08 22:06:33.019errorTypeError: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:33.016erroruncaught exception: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:29.791infostarting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.tr-064, node: v6.11.3
-- | --
host.raspberrypi2017-10-08 22:06:33.098errorinstance system.adapter.tr-064.0 terminated with code 0 (OK)Caught2017-10-08 22:06:33.098errorby controller[0]: at closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)Caught2017-10-08 22:06:33.098errorby controller[0]: at emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)Caught2017-10-08 22:06:33.098errorby controller[0]: at emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)Caught2017-10-08 22:06:33.097errorby controller[0]: at Object.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)Caught2017-10-08 22:06:33.096errorby controller[0]: at Parser.emit (events.js:188:7)Caught2017-10-08 22:06:33.091errorby controller[0]: at emitOne (events.js:96:13)Caught2017-10-08 22:06:33.091errorby controller[0]: at Parser. (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)Caught2017-10-08 22:06:33.091errorby controller[0]: at /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17Caught2017-10-08 22:06:33.091errorby controller[0]: at arguments.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:70:22)Caught2017-10-08 22:06:33.091errorby controller[0]: at /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:148:43Caught2017-10-08 22:06:33.090errorby controller[0]: TypeError: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:33.048infoterminatingtr-064.02017-10-08 22:06:33.019errorat closeTag (/opt/iobroker/node_modules/sax/lib/sax.js:889:7)tr-064.02017-10-08 22:06:33.019errorat emitNode (/opt/iobroker/node_modules/sax/lib/sax.js:629:5)tr-064.02017-10-08 22:06:33.019errorat emit (/opt/iobroker/node_modules/sax/lib/sax.js:624:35)tr-064.02017-10-08 22:06:33.019errorat Object.onclosetag (/opt/iobroker/node_modules/xml2js/lib/parser.js:261:26)tr-064.02017-10-08 22:06:33.019errorat Parser.emit (events.js:188:7)tr-064.02017-10-08 22:06:33.019errorat emitOne (events.js:96:13)tr-064.02017-10-08 22:06:33.019errorat Parser. (/opt/iobroker/node_modules/xml2js/lib/parser.js:303:18)tr-064.02017-10-08 22:06:33.019errorat /opt/iobroker/node_modules/tr-O64/lib/Service.js:267:17tr-064.02017-10-08 22:06:33.019errorat arguments.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:70:22)tr-064.02017-10-08 22:06:33.019errorat /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:148:43tr-064.02017-10-08 22:06:33.019errorTypeError: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:33.016erroruncaught exception: Cannot read property 'name' of undefinedtr-064.02017-10-08 22:06:29.791infostarting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.tr-064, node: v6.11.3

Gruß
Matze

**Comment by SebastianSchultz** [comment]
Scheint bei 0.4.1 auch der Fall zu sein.

**Comment by soef** [comment]
Hallo, ok, ist in 0.4.2 behoben.

**Comment by Matzebhv** [comment]
Leider nein.


host.raspberrypi | 2017-10-15 20:01:21.044 | error | instance system.adapter.tr-064.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2017-10-15 20:01:21.044 | error | by controller[0]:     at closeTag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/sax/lib/sax.js:889:7)
Caught | 2017-10-15 20:01:21.044 | error | by controller[0]:     at emitNode (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/sax/lib/sax.js:629:5)
Caught | 2017-10-15 20:01:21.044 | error | by controller[0]:     at emit (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/sax/lib/sax.js:624:35)
Caught | 2017-10-15 20:01:21.043 | error | by controller[0]:     at Object.onclosetag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/parser.js:261:26)
Caught | 2017-10-15 20:01:21.043 | error | by controller[0]:     at Parser.emit (events.js:188:7)
Caught | 2017-10-15 20:01:21.043 | error | by controller[0]:     at emitOne (events.js:96:13)
Caught | 2017-10-15 20:01:21.043 | error | by controller[0]:     at Parser. (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/parser.js:303:18)
Caught | 2017-10-15 20:01:21.043 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.tr-064/node_modules/tr-O64/lib/Service.js:267:17
Caught | 2017-10-15 20:01:21.043 | error | by controller[0]:     at args.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:73:32)
Caught | 2017-10-15 20:01:21.042 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:158:34
Caught | 2017-10-15 20:01:21.042 | error | by controller[0]: TypeError: Cannot read property 'number' of undefined
tr-064.0 | 2017-10-15 20:01:20.993 | info | terminating
tr-064.0 | 2017-10-15 20:01:20.939 | error | at closeTag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/sax/lib/sax.js:889:7)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at emitNode (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/sax/lib/sax.js:629:5)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at emit (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/sax/lib/sax.js:624:35)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at Object.onclosetag (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/parser.js:261:26)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at Parser.emit (events.js:188:7)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at emitOne (events.js:96:13)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at Parser. (/opt/iobroker/node_modules/iobroker.tr-064/node_modules/xml2js/lib/parser.js:303:18)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at /opt/iobroker/node_modules/iobroker.tr-064/node_modules/tr-O64/lib/Service.js:267:17
tr-064.0 | 2017-10-15 20:01:20.939 | error | at args.(anonymous function) (/opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:73:32)
tr-064.0 | 2017-10-15 20:01:20.939 | error | at /opt/iobroker/node_modules/iobroker.tr-064/lib/deflections.js:158:34
tr-064.0 | 2017-10-15 20:01:20.939 | error | TypeError: Cannot read property 'number' of undefined
tr-064.0 | 2017-10-15 20:01:20.934 | error | uncaught exception: Cannot read property 'number' of undefined
tr-064.0 | 2017-10-15 20:01:17.684 | info | starting. Version 0.4.2 in /opt/iobroker/node_modules/iobroker.tr-064, node: v6.11.3
host.raspberrypi | 2017-10-15 20:01:15.216 | info | instance system.adapter.tr-064.0 started with pid 3922
host.raspberrypi | 2017-10-15 20:00:45.195 | info | Restart adapter system.adapter.tr-064.0 because enabled

**Comment by soef** [comment]
Besteht das Problem mit der aktuellen Version 0.4.4 weiterhin?

**Comment by PrinzEisenherz1** [comment]
Ja, Problem besteht auch mit der Version 0.4.4

**Comment by PrinzEisenherz1** [comment]
Ach ja, also node Version bei mir 6.11.4 und npm Version 3.10.10
Falls es vielleicht wichtig ist

**Comment by soef** [comment]
Hallo, das Problem sollte mit der Version 0.4.6 behoben sein.

**Comment by Matzebhv** [comment]
Moin,
jetzt funktionierts!
Gruß
Matze
