### ISSUE TITLE
Call forwarding

### ISSUE THREAD

**Issue by pancho23** [soef/ioBroker.tr-064#44]
Is there the possibility to add an option for de-/activate call forwarding?

**Comment by soef** [comment]
? ?

**Comment by pancho23** [comment]
It is no issue, only an improvement proposal

**Comment by soef** [comment]
Is now possible in Version 0.4.3

**Comment by pancho23** [comment]
How can it be implemented?

**Comment by soef** [comment]
I think the update will be available over night. or you install it manuel form npm.

**Comment by pancho23** [comment]
After activation of call forwarding directly in FRITZ!Box or FRITZ-App, there is no status update in ioBroker from false to true.

**Comment by soef** [comment]
If you have configured an update interval the call Forward states will be updated in this interval. Was fixed 6 days ago.

**Comment by pancho23** [comment]
thanks for excellent implementation, exactly what i am looking for
