### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by MarkSau** [soef/ioBroker.tr-064#54]
Hi..habe den Adapter neu installiert....ich bekomme ihn aber nicht ans laufen...Benutzer und Einstellungen an der FB sollten passen...Habe allerdings die neuste Labor Version auf meiner 7490..Log siehe Anhang
[Errorlog.txt](https://github.com/soef/ioBroker.tr-064/files/1589166/Errorlog.txt)

**Comment by soef** [comment]
I think you have installed a old version of soef module. At least version 0.4.10 must be used. Try npm update oder npm install in the iobroker/node_modules/iobroker-tr064 directory
