### ISSUE TITLE
AB kann nicht gesteuert werden

### ISSUE THREAD

**Issue by SpikeNbg** [soef/ioBroker.tr-064#55]
Ich habe versucht die Schalter tr-064.0.states.ab und tr-064.0.states.abIndex zu setzen.
Im Log stehen dann Fehler wie 
tr-064.0 | 2017-12-30 19:07:00.085 | error | TypeError: this.setEnableAB is not a function
tr-064.0 | 2017-12-30 19:07:00.085 | error | message tr-064.0.states.ab [object Object] this.setEnableAB is not a function
Bei einem Blick in "tr-064.js" sieht es so aus, als wären die Funktionen tatsächlich nicht da..
Aber so gut kenn ich JS auch nicht..
Vielen Dank fürs ansehen!

**Comment by SpikeNbg** [comment]
Ich hab es jetzt übers Command gelöst:

function disableAB() {
    var dp="tr-064.0.states.command"; //Datenpunkt command vom tr-064
    var command = { 
        "service": "urn:dslforum-org:service:X_AVM-DE_TAM:1", 
        "serviceIds": "urn:X_AVM-DE_TAM-com:serviceId:X_AVM-DE_TAM1",
        "action": "SetEnable", 
        "params": { 
            "NewIndex": "0", 
            "NewEnable": "0" 
        } 
    }; 
    var comm=JSON.stringify(command);  //Kommando als JSON
    setState(dp , comm);   
}

**Comment by SpikeNbg** [comment]
Vielleicht hilft das bei der Lösung des Bugs..
Vielen Dank nochmal und Grüße

**Comment by soef** [comment]
Normalerweise funktionieren die beiden Datenpunkte. Welche Version des ioBroker.tr-064 Adapter verwendest du? Die aktuelle Version ist 0.4.10.
Viele Grüße, 
soef.

**Comment by AlGu1** [comment]
Auch bei mir kommt der Fehler:
```
tr-064.0 | 2018-01-25 15:43:07.705 | error | TypeError: this.setEnableAB is not a function at TR064.setAB (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:302:10) at onStateChange (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.j
-- | -- | -- | --
tr-064.0 | 2018-01-25 15:43:07.703 | error | message tr-064.0.states.ab [object Object] this.setEnableAB is not a function
```
im Log wenn ich den AB ein oder ausschalten will.

Adapter Version: 0.4.10 und 0.4.14 beide haben das gleiche Verhalten.

Danke und Gruß
AlGu

**Comment by soef** [comment]
Komisch. Die Werte im Skript und im Adapter sind identisch. Funktioniert denn das Command-Skript, also wird der AB wirklich ein/ausgeschaltet? Oder gibt es nur keine Fehlermeldung?

Setzt doch einmal manuell (ioBroker.admin/Objects) tr-064.0.states.command auf 
dumpservices.fs
Anschließend müsste im ioBroker/log Verzeichnis eine Datei mit dem Namen tr-64-services.json erstellt worden sein. Sucht darin einmal nach X_AVM-DE_TAM:1 und schaut ob bei den Actions SetEnable vorhanden ist.

**Comment by AlGu1** [comment]
Das setzen des "Command" auf "dumpservices.fs" hat auch nur einen Fehler im Log erzeugt:

```
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Manager. (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Socket.onevent (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:48:30)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3190:37)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:23:31)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at onStateChange (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:158:45)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at TR064.command (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:568:14)
tr-064.0 | 2018-01-26 07:48:30.856 | error | at TR064.dumpServices (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:534:39)
tr-064.0 | 2018-01-26 07:48:30.856 | error | TypeError: Cannot read property 'services' of undefined
tr-064.0 | 2018-01-26 07:48:30.855 | error | message tr-064.0.states.command [object Object] Cannot read property 'services' of undefined
```

Es wird keine Datei im Log-Ordner erstellt. Ich hab auch noch mal geschaut ob der AB geschaltet wird oder nicht und leider wird er nicht mehr geändert. D.h. aktuell funktioniert der Adapter bei mir nicht. Brauchst du noch mehr infos für die Fehlersuche? Oder kann ich selber noch was machen?

Danke und Gruß
AlGu

**Comment by AlGu1** [comment]
Gerade gesehen dass noch ein weitere Log Eintrag kommt:

```
tr-064.0 | 2018-01-26 08:04:51.487 | error | ~
-- | -- | -- | --
tr-064.0 | 2018-01-26 08:04:51.487 | error | ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2018-01-26 08:04:51.487 | error | ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2018-01-26 08:04:51.487 | error | ~
tr-064.0 | 2018-01-26 08:04:51.486 | error | Error: read ECONNRESET - {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}

```
Ich habe die FB jetzt neu gestartet und teste noch mal...

**Comment by soef** [comment]
Gut das sich das geklärt hat...
