### ISSUE TITLE
Store "Last Active" parseable version (ISO Date?)

### ISSUE THREAD

**Issue by Apollon77** [soef/iobroker.tr-064#6]
Currently "lastActive" is stored in a very custom format which is good european human readable format but not really international and not really in a format that a script can work with it.

Please store it in a default format (ISO or such), so it is still readable, bit can also be converted and worked with (like "how long the device is offline now" and such cases)

Or store an additional timeStamp like in find-my-iphone adapter

**Comment by soef** [comment]
you are right. will be changed in version 0.1.8

**Comment by Apollon77** [comment]
worx, verified (installed from github :-)  )
