### ISSUE TITLE
Nach Deinstallation und Neuinstallation (inkl. aufräumen der Objekte) werden die Objekte nicht erneut angelegt

### ISSUE THREAD

**Issue by legien** [soef/ioBroker.tr-064#60]
Mir fehlen nach Deinstallation und Neuinstallation inkl. clean der Objekte und States alle zugehörigen Objekte (calllist, ... etc.).

Irgendeine Idee woran das liegen könnte?

**Comment by soef** [comment]
Hallo, ist der Adapter aktiviert? Gibt es Fehlermeldungen im Log? Username/Passwort richtig? Welche Datenpunkte sind vorhanden? Ist das Objekt der Instance (tr-064.0) vorhanden?

**Comment by legien** [comment]
Hi, ja der Adapter ist aktiviert. Leider gibt es keine Fehlermeldungen im Log. Username und Passwort habe ich mehrfach kontrolliert (hatte vorher auch schon funktioniert).

Tatsächlich gibt es nur einen Datenpunkt (tr-064.0):

`{
  "type": "meta",
  "common": {
    "name": "tr-064"
  },
  "native": {
    "loaded": true
  },
  "from": "system.adapter.tr-064.0",
  "ts": 1515883801075,
  "_id": "tr-064.0",
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by legien** [comment]
Hm, nach dem neusten Update und einer neuen Installation haben sich wieder alle Objekte aufgebaut .. sehr komisch. Ich mach dann dieses Issue aber erstmal zu.
