### ISSUE TITLE
Änderungen zwischen 0.4.10 und Aktuell 0.4.15 ?

### ISSUE THREAD

**Issue by wendy2702** [soef/ioBroker.tr-064#63]
Hi,

was sind denn die Änderungen zwischen 0.4.10 und 0.4.15?

Leider hört das changelog bei 0.4.10 auf und bevor ich die neue Version installiere wüsste ich gerne was geändert worden ist.

Danke und Gruß

**Comment by soef** [comment]
Hab'  das changelog in der readme einmal auf den aktuellen Stand gebracht. Auf github waren die durchgeführten Änderungen aber sichtbar.
