### ISSUE TITLE
Datenpunkt "IP" und MAC einfügen

### ISSUE THREAD

**Issue by mikiline** [soef/ioBroker.tr-064#65]
Hallo,

vielen Dank für die tolle Arbeit bisher!
Wäre es möglich noch 2 Datenpunkte einzufügen um diese direkt per "State" abrufen zu können?

Das wären die IP und die MAC Adresse.......die unter "active" oder "last-active" setzen

Danke und Gruss
mikiline

**Comment by soef** [comment]
Hallo, 

hab' die Datenpunkte lastIP und lastMAC-address einmal den Geräten hinzugefügt. 

Eigentlich sind die IP und MAC aber uninteressant, da sie für das jeweilige Gerät immer gleich bleiben. Zumindest, wenn man - wie ich es für wichtige Geräte mache - in der FritzBox unter Heimnetz -> Netzwerk die Checkbox für "Diesem Netzwerkgerät immer die gleiche IPv4-Adresse zuweisen" aktiviert.

Viele Grüße

**Comment by soef** [comment]
Ist in der Version 0.4.18 aufgenommen.

**Comment by mikiline** [comment]
Super, Danke Dir.....mir geht es da um eine Netzwerkanzeige (grafische Übersicht). ich habe auch nicht bei allen die feste IP zugewiesen....Lease wird erneuert
