### ISSUE TITLE
not possible to enable/disable call forwarding

### ISSUE THREAD

**Issue by wendy2702** [soef/ioBroker.tr-064#66]
Hi,

it looks that the status at "Objects" is not correct. Because of this it's not possible to enable/disable call forwarding.

Installed Version 0.4.18

![call_forwarding](https://user-images.githubusercontent.com/33424168/36861163-6acc8504-1d83-11e8-88b7-f1d729ca018b.jpg)

**Comment by pschmalz** [comment]
Hallo zusammen,
ich habe genau das gleiche Problem. Leider keine Einträge unter "callForwarding".
Sowohl mit Version 0.4.18, als auch mit älteren Versionen.
Meine FritzBox ist ein 6490 Cable mit Firmware 06.87 (kdg Branding).

**Comment by wendy2702** [comment]
Hi,

it seems that you need to configure a rule for incoming/outgoing calls:

![ruf_regel](https://user-images.githubusercontent.com/33424168/37646059-e299f16c-2c28-11e8-86bd-8e3bc4cf1517.jpg)

After i created the rule and restarted the TR-064 adapter i got this under objects:

![tr-064_objecte](https://user-images.githubusercontent.com/33424168/37646158-2671eda4-2c29-11e8-90cd-391fd24252c3.jpg)

Activation/Deactivation of call forwarding is working fine now.

You can also check this thread at iobroker forum: https://forum.iobroker.net/viewtopic.php?f=20&t=12248&start=20
