### ISSUE TITLE
Ring State with duration

### ISSUE THREAD

**Issue by foxriver76** [soef/ioBroker.tr-064#71]
Hi,

I just tried to do a setState on the ring state with duration value, but it dosen't seem to work.

The documentation says
> When using an internel number (like **610) the ring state will let ring that internal phone. e.g.: **610[,timeout]
 
According to this I tried several versions:
`setState('tr-064.0.states.ring', '**611 [2000]'); // tried ms as duration value`
`setState('tr-064.0.states.ring', '**611 [,2000]'); // tried ms as duration value with comma`
`setState('tr-064.0.states.ring', '**611 [2]');  // tried sec as duration value`
`setState('tr-064.0.states.ring', '**611 [,2]');  // tried sec with comma`

But none of these seem to work. Could you tell me what is wrong with these statements?

best regards

fox

**Comment by foxriver76** [comment]
it works with **611 , 2 --> Blank space before the comma seems to be very important.

**Comment by soef** [comment]
Hi, usually it works without spaces. Condition is an activated dialing assistance and an assigned telephone in the Fritzbox. (Telefonie -> Telefonbuch -> Wahlhilfe)
