### ISSUE TITLE
Verwende MDNS zum triggern der Aktuallisierung

### ISSUE THREAD

**Issue by ihavenonick** [soef/ioBroker.tr-064#77]
Ich mache meine Anwesenheitserkennung über Dein Adapter und MDNS sollte schneller sein als das Polling. Leider habe ich damit ein Problem. MDNS ist aktiv, aber die Aktualisierung erfolgt nach dem eingestellten Polling Intervall. Trage ich beim Intervall nichts ein, wird überhaupt nicht aktualisiert. Somit läuft das MDNS wohl überhaupt nicht. Liegt das am Adapter, oder habe ich was falsch verstanden?
Ich möchte nicht unbedingt alle 30 Sekunden ein Polling ausführen, nur um eine rechte schnelle Anwesenheitserkennung zu realisieren. Ich bin hier dankbar für jeden Tipp.
Fritz 7490
FRITZ!OS: 06.98-60269 BETA
node: 8.11.3
nodejs: 8.11.3
npm: 4.6.1

**Comment by BamBam191** [comment]
Schließe mich dem Vorredner an und wäre für eine Hilfestellung dankbar.

**Comment by BamBam191** [comment]
> Ich mache meine Anwesenheitserkennung über Dein Adapter und MDNS sollte schneller sein als das Polling. Leider habe ich damit ein Problem. MDNS ist aktiv, aber die Aktualisierung erfolgt nach dem eingestellten Polling Intervall. Trage ich beim Intervall nichts ein, wird überhaupt nicht aktualisiert. Somit läuft das MDNS wohl überhaupt nicht. Liegt das am Adapter, oder habe ich was falsch verstanden?
> Ich möchte nicht unbedingt alle 30 Sekunden ein Polling ausführen, nur um eine rechte schnelle Anwesenheitserkennung zu realisieren. Ich bin hier dankbar für jeden Tipp.
> Fritz 7490
> FRITZ!OS: 06.98-60269 BETA
> node: 8.11.3
> nodejs: 8.11.3
> npm: 4.6.1

Hast du zufällig schon eine Lösung gefunden?

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.tr-064-community#24
