### ISSUE TITLE
Adapter crashes on startup while looking for Guest Wlan

### ISSUE THREAD

**Issue by Jey-Cee** [soef/ioBroker.tr-064#8]
Hi,

adapter crashes on startup while looking for guest wlan. I am using Fritz Box 7360.

Here is the error log:
`tr-064.0	2017-01-01 12:54:06.797	info	terminating
tr-064.0	2017-01-01 12:54:06.789	error	at Timer.listOnTimeout (timers.js:92:15)
tr-064.0	2017-01-01 12:54:06.789	error	at doIt [as _onTimeout] (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:476:32)
tr-064.0	2017-01-01 12:54:06.789	error	at TR064.getWLANGuest (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:349:76)
tr-064.0	2017-01-01 12:54:06.789	error	TypeError: Cannot read property 'actions' of undefined
tr-064.0	2017-01-01 12:54:06.785	error	uncaught exception: Cannot read property 'actions' of undefined
tr-064.0	2017-01-01 12:54:03.865	info	starting. Version 0.1.12 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.4.7`

**Comment by soef** [comment]
changed in Version 1.14. Do you know the correct path to the GetInfo function for your Fritz.box?

**Comment by Jey-Cee** [comment]
No i don't know it. But i found information on the internet that it is possible that avm has removed this feature. But this is not confirmed now.
