### ISSUE TITLE
Probleme bei zwei parallelen Telefonaten

### ISSUE THREAD

**Issue by maeb3** [soef/ioBroker.tr-064#84]
Bei mir sind mehrere Telefonnummern in der Fritzbox hinterlegt und es können mehrere Gespräche gleichzeitig geführt werden. 
Wenn parallel Telefonate geführt werden, wird beim zweiten Anruf die Richtung (sym) nicht in die JSON-Anrufliste eingetragen. 

Beispiel (Telefonnummern wurden im Beispiel ersetzt):
`...
{"id":5666,"type":"3","called":"06221xxxxxx","caller":"SIP: yyyyyyyy","callernumber":"yyyyyyyy","name":"bbbbbbbb","numbertype":"sip","device":"FritzFon 2","port":"10","date":"27.12.18 17:38","duration":"0:11","count":"","path":"",**"sym":"<"**,"external":"06221xxxxxx"},
{"id":5667,"type":"9","caller":"06221xxxxxx","called":"SIP: yyyyyyyy","callednumber":"yyyyyyyy","name":"cccccccc","numbertype":"sip","device":"AB","port":"40","date":"27.12.18 17:47","duration":"0:03","count":"","path":"","external":"06221xxxxxx"},
...`

Beim ersten Anruf (11 Minuten ab 17:38 Uhr) wird die Richtung noch gezeigt (sym: <).
Beim zweiten Anruf (3 Minuten ab 17:47 Uhr) fehlt der sym-Eintrag.

Dies passiert immer dann, wenn sich zwei Anrufe zeitlich überlappen.

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.tr-064-community#31

**Comment by maeb3** [comment]
Done
