### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [soef/ioBroker.tr-064#89]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/soef/ioBroker.tr-064

- [ ] [E019] Invalid repository URL: https://github.com/soef/iobroker.tr-064. Expected: git+https://github.com/soef/ioBroker.tr-064.git
- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E109] desc in io-package.json should be an object for many languages. Found only TR 064
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E115] No license found in io-package.json
- [ ] [E130] Too many news found in io-package.json. Mast be less than 21. Please remove old news.
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E405] Icon must be in the following path: https://raw.githubusercontent.com/soef/ioBroker.tr-064/master/
- [ ] [E407] Meta URL(latest) must be equal to https://raw.githubusercontent.com/soef/ioBroker.tr-064/master/io-package.json
- [ ] [E426] Icon(stable) must be in the following path: https://raw.githubusercontent.com/soef/ioBroker.tr-064/master/
- [ ] [E428] Meta URL(stable)  must be equal to https://raw.githubusercontent.com/soef/ioBroker.tr-064/master/io-package.json
- [ ] [E506] More non translated in german or russian words found in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] [E802] No topics found in the repository. Please go to "https://github.com/soef/ioBroker.tr-064", press the settings button beside the about title and add some topics.
- [ ] [E604] No "## License" found in README.md

I have also found warnings that may be fixed if possible.

- [ ] [W113] Adapter should support compact mode

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.tr-064-community#3

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
