### ISSUE TITLE
Adapter Startet nicht

### ISSUE THREAD

**Issue by billy995** [soef/ioBroker.tr-064#96]
host.ioBroker | 2019-09-22 19:10:25.491 | info | Restart adapter system.adapter.tr-064.0 because enabled
-- | -- | -- | --
host.ioBroker | 2019-09-22 19:10:25.491 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
host.ioBroker | 2019-09-22 19:10:25.491 | error | Caught by controller[0]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at startup (internal/bootstrap/node.js:283:19)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:653:32)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:776:30)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:15:20)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:     at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.ioBroker | 2019-09-22 19:10:25.490 | error | Caught by controller[0]:                       ^
host.ioBroker | 2019-09-22 19:10:25.489 | error | Caught by controller[0]:     fns.adapter = fns.adapter(options);
host.ioBroker | 2019-09-22 19:10:25.487 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
host.ioBroker | 2019-09-22 19:10:24.353 | info | instance system.adapter.tr-064.0 started with pid 14526
host.ioBroker | 2019-09-22 19:09:54.318 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.ioBroker | 2019-09-22 19:09:54.318 | error | instance system.adapter.tr-064.0 terminated with code 1 ()

**Comment by matze19999** [comment]
service iobroker start && cd /opt/iobroker/node_modules/iobroker.tr-064/ && npm install soef
